version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-tasks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres-data: